name: SNF Test

on: workflow_dispatch

jobs:
  SNF:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      GROUP_ID: ${{ secrets.GROUP_ID }}
      REPO_URL: $$ {{ github.repository }}
    steps:
      - name: snf
        run: |
          python3 <<EOF
          import requests
          import json
          import sys

          token = os.environ["SNYK_TOKEN"]
          group_id = os.environ["GROUP_ID"]
          repo_url = os.environ["REPO_URL"]

          url = f"https://api.snyk.io/closed-beta/groups/{group_id}/assets/search?version=2024-10-15"
          headers = {
              "authorization": token,
              "accept": "application/vnd.api+json",
              "Content-Type": "application/json"
          }
          payload = json.dumps({
            "query": {
              "attributes": {
                "attributes": "respository_url",
                "operator": "contains",
                "values": [
                  f"https://github.com/{repo_url}"
                ]
          response = requests.request("POST", url, headers=headers, data=payload)
          print (response.text)
