name: Snyk Container Scan

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node.js dependencies
        run: npm install

      - name: Install Snyk CLI
        run: npm i -g snyk

      - name: Verify Snyk CLI Installation
        run: snyk --version

      - name: Set up Snyk authentication
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Build Docker image
        run: |
          docker build . -t juice-shop:latest
          docker images # List images to confirm build

      - name: Snyk container scan
        run: |
          snyk container monitor juice-shop:latest --org=9e215830-3e7b-4adc-b3e0-f85cdc08aea3 --exclude-app-vulns --file=Dockerfile
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} # Ensure token is passed here too


